"""add users table

Revision ID: d0b65365c266
Revises: 90c2c90bc00e
Create Date: 2026-09-23 19:22:32.424972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b65365c266'
down_revision: Union[str, Sequence[str], None] = '90c2c90bc00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_title', sa.String(length=255), nullable=False),
    sa.Column('app_description', sa.String(length=1024), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=False),
    sa.Column('app_debug', sa.Boolean(), nullable=False),
    sa.Column('uvicorn_host', sa.String(length=255), nullable=False),
    sa.Column('uvicorn_port', sa.Integer(), nullable=False),
    sa.Column('uvicorn_log_level', sa.String(length=32), nullable=False),
    sa.Column('uvicorn_reload', sa.Boolean(), nullable=False),
    sa.Column('storage_dir', sa.String(length=2048), nullable=False),
    sa.Column('database_url', sa.String(length=2048), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('auto_start', sa.Boolean(), nullable=False),
    sa.Column('open_browser', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_settings')
    # ### end Alembic commands ###
